DROP DATABASE IF EXISTS tododb;

CREATE DATABASE tododb;

USE tododb;

CREATE TABLE PRODUCT (
ID int NOT NULL AUTO_INCREMENT,
DESCRIPTION varchar(50) NOT NULL,
COMPLETION varchar(50) NOT NULL,
STATUS int NOT NULL,
PRIMARY KEY(ID) 
)